### ISSUE TITLE
Country Codes

### ISSUE THREAD

**Issue by sebgie** [gitterHQ/vat-calculator#3]
I have a bit of trouble using my existing country codes with vat-calculator. I'm using the library without integration to third party services atm. The country codes are not following one standard and are not consistent for United Kingdom (ISO 3611) and Greece (EU).

From http://publications.europa.eu/code/pdf/370000en.htm:

>The two-letter ISO code should be used (ISO 3166 alpha-2), except for Greece and the United Kingdom, for which the abbreviations EL and UK are recommended.

The problem I ran into is that we use a legacy DB which uses ISO 3611 country codes and Greece is referenced as `GR` instead of `EL`. Therefore I wanted to ask if it would be possible to also add `UK` and `GR` to `standard-european-vat-rates.js` to make it work with older databases?

**Comment by sebgie** [comment]
Update: Octobat also doesn't recognize `EL` or `UK` as valid country code:

Request: `POST http://vatmoss.octobat.com/vat.json`
Body:
```
{
    "supplier": {"country": "GB"},
    "customer": {"country": "EL"},
    "transaction": {"type": "B2C", "eservice": true}
}
```
Response:
```
{"error":{"message":"{\"name\":\"in_eu?\",\"args\":[]}","code":500}}
```

**Comment by suprememoocow** [comment]
Hi @sebgie, thanks for the PR. John suggested that I add you as a contributor to the project. I'm happy to do this if you're willing. Let me know!

**Comment by suprememoocow** [comment]
On second thoughts, I'll need to move the repo to my own account as I can't give you collaborator access without adding you to the GitterHQ org. For the moment, let's stick with PRs and if it becomes a problem we can move the repo.

Also, you're always welcome to ping me if I haven't replied to a PR within a few days - I'm not being rude, it's just the sheer number of PRs and issues I get on my GitHub account I sometimes miss things :)

**Comment by sebgie** [comment]
Hey @suprememoocow!
Sure, I'm happy to help maintaining vat-calculator. PRs are fine for me. Seems like we have the same problem with GH notification overload. I'll ping you next time a PR is sitting around for too long ;-).
